import Head from 'next/head'
import { useEffect, useState } from 'react'
import { path } from 'd3-path'
import { animated, useSpring, useTransition } from 'react-spring'
// https://dev.to/tomdohnal/react-svg-animation-with-react-spring-4-2kba

type Co2Year = { year: number; co2: number }

const max = (array: Array<Co2Year>, key: 'year' | 'co2') => {
  return Math.max(...array.map((d) => d[key]))
}
const min = (array: Array<Co2Year>, key: 'year' | 'co2') => {
  return Math.min(...array.map((d) => d[key]))
}

const line = (
  data: Array<Co2Year>,
  {
    width = 500,
    height = 240,
    maxYear = max(data, 'year'),
    minYear = min(data, 'year'),
    maxCo2 = max(data, 'co2'),
    minCo2 = min(data, 'co2'),
  }: {
    width?: number
    height?: number
    maxYear?: number
    minYear?: number
    maxCo2?: number
    minCo2?: number
  },
) => {
  if (!data.length) return ''
  const p = path()

  const normalizedData = data.map((d: { year: number; co2: number }) => ({
    x: ((d.year - minYear) * width) / (maxYear - minYear),
    y: height - (d.co2 / maxCo2) * height,
  }))
  console.log({ maxCo2, minCo2, normalizedData })
  // start at the top left
  p.moveTo(normalizedData[0].x, normalizedData[0].y)

  // draw all the datapoints
  normalizedData.forEach((d) => p.lineTo(d.x, d.y))

  // draw the bottom of the line
  p.lineTo(normalizedData[normalizedData.length - 1]?.x || 0, height)
  p.lineTo(normalizedData[0].x, height)
  p.lineTo(normalizedData[0].x, normalizedData[0].y)
  p.closePath()
  return p.toString()
}

const Graph = () => {
  const [loaded, setLoaded] = useState(false)
  const [showNow, setShowNow] = useState(false)
  const [showParis, setShowParis] = useState(false)
  const [showPledges, setShowPledges] = useState(false)
  const [width, height] = [500, 240]
  const [year, setYear] = useState({ year: 1990 })

  useEffect(() => {
    setTimeout(() => setLoaded(true), 300)
  }, [])

  const data = [
    { year: 1990, co2: 244858 },
    { year: 1991, co2: 247335 },
    { year: 1992, co2: 249812 },
    { year: 1993, co2: 252289 },
    { year: 1994, co2: 254766 },
    { year: 1995, co2: 257243 },
    { year: 1996, co2: 259720 },
    { year: 1997, co2: 262197 },
    { year: 1998, co2: 264674 },
    { year: 1999, co2: 267151 },
    { year: 2000, co2: 269628 },
    { year: 2001, co2: 272967.8 },
    { year: 2002, co2: 276307.6 },
    { year: 2003, co2: 279647.4 },
    { year: 2004, co2: 282987.2 },
    { year: 2005, co2: 286327 },
    { year: 2006, co2: 294968 },
    { year: 2007, co2: 303609 },
    { year: 2008, co2: 312250 },
    { year: 2009, co2: 320891 },
    { year: 2010, co2: 329532 },
    { year: 2011, co2: 202260 },
    { year: 2012, co2: 197892 },
    { year: 2013, co2: 172924 },
    { year: 2014, co2: 138393 },
    { year: 2015, co2: 142491 },
    { year: 2016, co2: 139340 },
    { year: 2017, co2: 125147 },
    { year: 2018, co2: 146469 },
    { year: 2019, co2: 115844 },
  ]

  const pledges = [
    { year: 2019, co2: 115844 },
    { year: 2020, co2: 114844 },
    { year: 2021, co2: 113844 },
    { year: 2022, co2: 112844 },
    { year: 2023, co2: 111844 },
    { year: 2024, co2: 110000 },
    { year: 2025, co2: 109000 },
    { year: 2026, co2: 108000 },
    { year: 2027, co2: 107000 },
    { year: 2028, co2: 106000 },
    { year: 2029, co2: 105000 },
    { year: 2030, co2: 104000 },
  ]

  const paris = [
    //{ year: 2014, co2: 138393 },
    { year: 2019, co2: 115844 },
    { year: 2020, co2: 82491 },
    { year: 2021, co2: 66491 },
    { year: 2022, co2: 30340 },
    { year: 2023, co2: 20147 },
    { year: 2024, co2: 15844 },
    { year: 2025, co2: 14844 },
    { year: 2026, co2: 13844 },
    { year: 2027, co2: 12844 },
    { year: 2028, co2: 10844 },
    { year: 2029, co2: 5844 },
    { year: 2030, co2: 0 },
  ]

  const glappet = paris.map((d, i) => ({
    year: d.year,
    co2: pledges[i].co2 - d.co2,
  }))

  return (
    <>
      <Head>
        <title>Klimatkollen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={loaded ? 'loaded' : ''}>
        <svg viewBox={`0 0 ${width} ${height}`}>
          <defs>
            <filter id="dropshadow">
              <feGaussianBlur in="SourceAlpha" stdDeviation="3"></feGaussianBlur>
              <feOffset dx="0" dy="0" result="offsetblur"></feOffset>
              <feComponentTransfer>
                <feFuncA slope="0.2" type="linear"></feFuncA>
              </feComponentTransfer>
              <feMerge>
                <feMergeNode></feMergeNode>
                <feMergeNode in="SourceGraphic"></feMergeNode>
              </feMerge>
            </filter>
          </defs>
          <g className="datasets">
            <animated.path
              className="dataset"
              d={line(data, {
                minYear: 1990,
                maxYear: 2030,
                width,
                height,
                maxCo2: max(data, 'co2'),
              })}
              id="dataset-1"></animated.path>
            {showPledges && (
              <animated.path
                className="dataset"
                d={line(pledges, {
                  minYear: 1990,
                  maxYear: 2030,
                  maxCo2: max(data, 'co2'),
                })}
                id="dataset-2"></animated.path>
            )}
            {showParis && (
              <animated.path
                className="dataset"
                d={line(paris, {
                  minYear: 1990,
                  maxYear: 2030,
                  width,
                  height,
                  maxCo2: max(data, 'co2'),
                })}
                id="dataset-3"></animated.path>
            )}

            {/* <animated.path
              className="dataset"
              d="M0,260 C35,254 63,124 88,124 C114,124 148,163 219,163 C290,163 315,100 359,100 C402,100 520,244 560,259 C560,259 0,259 0,260 Z"
              id="dataset-2"></animated.path>
            <animated.path
              className="dataset"
              d="M0,260 C0,260 22,199 64,199 C105,199 112,144 154,144 C195,144 194,126 216,126 C237,126 263,184 314,184 C365,183 386,128 434,129 C483,130 511,240 560,260 L0,260 Z"
              id="dataset-1"></animated.path> */}
          </g>
        </svg>
      </div>

      <button onClick={() => setShowNow(!showNow)}>Historiskt</button>
      <button onClick={() => setShowParis(!showParis)}>Paris</button>
      <button onClick={() => setShowPledges(!showPledges)}>Prognos</button>
    </>
  )
}

export default Graph
