# -*- coding: utf-8 -*-
"""CPEV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FmvETyXK1reu6xtNDGQBgtGMq5yjMaN
"""

import numpy as np

# import matplotlib.pyplot as plt
# from scipy.stats import linregress

years = np.arange(2015, 2022 + 1, 1)

ref_CPEV = 0.1  # chargers per 10 electric cars (this should be the proper value but I set it to something different to make oother steps more clear)

np.random.seed(4)

CPEV = np.random.normal(loc=1, scale=0.5, size=(len(years)))
print("CPEV:", CPEV)

# plt.plot(years, CPEV, marker='o', linestyle='--', color = 'b', label='Data points')
# plt.hlines(ref_CPEV, years[0], years[-1], linestyle='--', color='k', label = 'EU goal')
# plt.title('The CPEV for each year together with the stated EU goal')
# plt.legend()
# plt.grid()
# plt.show()

# plt.plot(years, CPEV, marker='o', linestyle='--', color = 'b', label='Data points')

# Plot horizontal reference line
# plt.hlines(ref_CPEV, years[0], years[-1], linestyle='--', color='k', label = 'EU goal')

# Add arrows between data points and reference line
# for year, cpev in zip(years, CPEV):
#     plt.annotate('', xy=(year, ref_CPEV), xytext=(year, cpev),
#                  arrowprops=dict(facecolor='red', shrink=0.01))

# plt.title('The CPEV for each year together with the stated EU goal')
# plt.legend()
# plt.grid()
# plt.show()

"""What is the average distance from the reference?"""

m = np.mean(CPEV - ref_CPEV) * 100
print(m)

# plt.plot(years, CPEV, marker='o', linestyle='--', color = 'b', label='Data points')
# plt.hlines(ref_CPEV, years[0], years[-1], linestyle='--', color='k', label = 'EU goal')
# plt.hlines(ref_CPEV+np.mean(CPEV-ref_CPEV), years[0], years[-1], linestyle='-.', color='g', label = 'Average level over time')
# plt.title('The average CPEV and for each year together with the stated EU goal')
# plt.legend()
# plt.grid()
# plt.show()

"""This municipality have, on average:"""
r = (ref_CPEV + np.mean(CPEV - ref_CPEV)) / ref_CPEV * 100
print(r, "%")

"""of the EU goal."""


print(r - m)
