import Head from 'next/head'
import { useState } from 'react'
import styled from 'styled-components'
import DropDown from '../components/DropDown'
import Map from '../components/Map'
import { H1, Paragraph } from '../components/Typography'
import { Municipality } from '../utils/types'
// import Municipality from './kommun/[municipality]'
// import Municipality from './kommun/[municipality]'

type PropsType = {
  municipalities: Array<Municipality>
}
const Box = styled.div`
  width: 195px;
  height: 34px;
  background-color: #fff;
  border-radius: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
`

const InfoText = styled.p`
  color: black;
`

const Home: React.FC<PropsType> = ({ municipalities }: PropsType) => {
  const [selected, setSelected] = useState()
  const municipalitiesName = municipalities.map((item) => item.Name)
  const emissionsLevels = municipalities.map((item) => ({
    name: item.Name,
    emissions: item.EmissionLevelChangeAverage,
  }))

  return (
    <>
      <Head>
        <title>Klimatkollen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <H1>Klimatkollen</H1>
      <Paragraph>
        Låt oss ta tempen på hur väl din kommun når upp till de mål som är uppsatta i
        parisavtalet.
      </Paragraph>
      <DropDown municipalitiesName={municipalitiesName} />
      {selected && (
        <Box>
          <InfoText>{selected}</InfoText>
        </Box>
      )}
      <Map emissionsLevels={emissionsLevels} setSelected={setSelected} />
    </>
  )
}

export async function getServerSideProps() {
  const municipalities = await fetch(
    'http://klimatkollen.vercel.app/api/municipalities',
  ).then((res) => res.json())
  return {
    props: { municipalities },
  }
}

export default Home
