import { useState } from 'react'
import Head from 'next/head'
import DropDown from '../components/DropDown'
import Graph from '../components/Graph'
import { H1, Paragraph } from '../components/Typography'
import { Municipality } from '../utils/types'
import { data, pledges, paris } from '../data/stockholm'

type PropsType = {
  municipalities: Array<Municipality>
}

const Home: React.FC<PropsType> = ({ municipalities }: PropsType) => {
  const municipalitiesName = municipalities.map((item) => item.Name)
  const [currentStep, setCurrentStep] = useState(1)

  return (
    <>
      <Head>
        <title>Klimatkollen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data?.length && paris?.length && pledges?.length && (
        <Graph
          width={500}
          height={250}
          currentStep={currentStep}
          data={data}
          paris={paris}
          pledges={pledges}
        />
      )}
      {currentStep < 4 && (
        <button onClick={() => setCurrentStep((current) => current + 1)}>nästa</button>
      )}

      {currentStep != 1 && (
        <button onClick={() => setCurrentStep((current) => current - 1)}>
          förgående
        </button>
      )}
      <H1>Klimatkollen</H1>
      <Paragraph>
        Låt oss ta tempen på hur väl din kommun når upp till de mål som är uppsatta i
        parisavtalet.
      </Paragraph>
      <DropDown municipalitiesName={municipalitiesName} />
    </>
  )
}

export async function getServerSideProps() {
  const municipalities = await fetch(
    'http://klimatkollen.vercel.app/api/municipalities',
  ).then((res) => res.json())
  return {
    props: { municipalities },
  }
}

export default Home
